<?php
$filmesDestaques = [
  [ "img" => "/projetotadscinetime/public/assets/images/filme1.webp",  "titulo" => "DEXTER", "desc" => "Um serial killer que caça criminosos em Miami." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme2.jpg",   "titulo" => "CARROS", "desc" => "Relâmpago McQueen em uma jornada de amizade." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme3.png",   "titulo" => "CORINGA", "desc" => "A origem do maior vilão de Gotham City." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme4.webp",  "titulo" => "ARRANHA-CÉU", "desc" => "Ação intensa em um arranha-céu em chamas." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme5.jpg",   "titulo" => "AVENGERS", "desc" => "Heróis se unem para salvar o mundo." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme6.webp",  "titulo" => "HOMEM ARANHA LONGE DE CASA", "desc" => "Peter enfrenta novos desafios na Europa." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme7.jpeg",  "titulo" => "SEM VOLTA PARA CASA", "desc" => "Peter Parker enfrenta vilões do multiverso." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme8.jpg",   "titulo" => "A MENINA E O DRAGÃO", "desc" => "Uma jornada mágica entre amizade e fantasia." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme9.jpg",   "titulo" => "VELOZES E FURIOSOS 10", "desc" => "Alta velocidade e família em primeiro lugar." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme10.jpg",  "titulo" => "GUERRA INFINITA", "desc" => "Thanos ameaça todo o universo." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme11.jpg",  "titulo" => "STRANGER THINGS", "desc" => "Mistérios sobrenaturais em Hawkins." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme12.jpg",  "titulo" => "CÓDIGO ALARUM", "desc" => "Suspense e tecnologia eletrizante." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme13.jpg",  "titulo" => "SNEAKS", "desc" => "Comédia e aventura única." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme14.jpg",  "titulo" => "O LADRÃO DE RAIOS", "desc" => "Percy Jackson descobre ser filho de deus." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme15.jpg",  "titulo" => "THOR", "desc" => "O deus do trovão enfrenta batalhas épicas." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme16.jpeg", "titulo" => "GUERRA CIVIL", "desc" => "Heróis divididos em conflito marcante." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme17.jpg",  "titulo" => "DIA DE MUERTOS", "desc" => "Uma celebração cultural cheia de vida." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme18.jpg",  "titulo" => "THE LAST WARRIOR", "desc" => "Um herói enfrenta batalhas épicas." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme19.jpeg", "titulo" => "THE WORLD OF IT", "desc" => "O terror do universo de Stephen King." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme20.jpg",  "titulo" => "CAPITÃO AMÉRICA", "desc" => "Steve Rogers luta pela liberdade." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme2.jpg",   "titulo" => "CARROS", "desc" => "Relâmpago McQueen em uma jornada." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme7.jpeg",  "titulo" => "SEM VOLTA PARA CASA", "desc" => "Peter enfrenta vilões do multiverso." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme11.jpg",  "titulo" => "STRANGER THINGS", "desc" => "Aventura sobrenatural em Hawkins." ],
];

$filmesPopulares = [
  [ "img" => "/projetotadscinetime/public/assets/images/filme19.jpeg", "titulo" => "THE WORLD OF IT", "desc" => "O terror do universo de Stephen King." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme15.jpg",  "titulo" => "THOR", "desc" => "O deus do trovão enfrenta batalhas épicas." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme20.jpg",  "titulo" => "CAPITÃO AMÉRICA", "desc" => "Steve Rogers luta pela liberdade." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme14.jpg",  "titulo" => "O LADRÃO DE RAIOS", "desc" => "Percy Jackson descobre ser filho de deus." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme11.jpg",  "titulo" => "STRANGER THINGS", "desc" => "Mistérios sobrenaturais em Hawkins." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme4.webp",  "titulo" => "ARRANHA-CÉU", "desc" => "Ação intensa em um arranha-céu em chamas." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme3.png",   "titulo" => "CORINGA", "desc" => "A origem do maior vilão de Gotham City." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme5.jpg",   "titulo" => "AVENGERS", "desc" => "Heróis se unem para salvar o mundo." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme6.webp",  "titulo" => "HOMEM ARANHA LONGE DE CASA", "desc" => "Peter enfrenta novos desafios na Europa." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme8.jpg",   "titulo" => "A MENINA E O DRAGÃO", "desc" => "Uma jornada mágica entre amizade e fantasia." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme9.jpg",   "titulo" => "VELOZES E FURIOSOS 10", "desc" => "Alta velocidade e família em primeiro lugar." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme10.jpg",  "titulo" => "GUERRA INFINITA", "desc" => "Thanos ameaça todo o universo." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme12.jpg",  "titulo" => "CÓDIGO ALARUM", "desc" => "Suspense e tecnologia eletrizante." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme13.jpg",  "titulo" => "SNEAKS", "desc" => "Comédia e aventura única." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme2.jpg",   "titulo" => "CARROS", "desc" => "Relâmpago McQueen em uma jornada de amizade." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme7.jpeg",  "titulo" => "SEM VOLTA PARA CASA", "desc" => "Peter Parker enfrenta vilões do multiverso." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme16.jpeg", "titulo" => "GUERRA CIVIL", "desc" => "Heróis divididos em conflito marcante." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme17.jpg",  "titulo" => "DIA DE MUERTOS", "desc" => "Uma celebração cultural cheia de vida." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme18.jpg",  "titulo" => "THE LAST WARRIOR", "desc" => "Um herói enfrenta batalhas épicas." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme1.webp",  "titulo" => "DEXTER", "desc" => "Um serial killer que caça criminosos em Miami." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme2.jpg",   "titulo" => "CARROS", "desc" => "Relâmpago McQueen em uma jornada." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme7.jpeg",  "titulo" => "SEM VOLTA PARA CASA", "desc" => "Peter enfrenta vilões do multiverso." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme11.jpg",  "titulo" => "STRANGER THINGS", "desc" => "Aventura sobrenatural em Hawkins." ],

];

$filmesMelhorAvaliados = [
  [ "img" => "/projetotadscinetime/public/assets/images/filme15.jpg",  "titulo" => "THOR", "desc" => "O deus do trovão enfrenta batalhas épicas." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme7.jpeg",  "titulo" => "SEM VOLTA PARA CASA", "desc" => "Peter Parker enfrenta vilões do multiverso." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme2.jpg",   "titulo" => "CARROS", "desc" => "Relâmpago McQueen em uma jornada de amizade." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme20.jpg",  "titulo" => "CAPITÃO AMÉRICA", "desc" => "Steve Rogers luta pela liberdade." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme11.jpg",  "titulo" => "STRANGER THINGS", "desc" => "Mistérios sobrenaturais em Hawkins." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme16.jpeg", "titulo" => "GUERRA CIVIL", "desc" => "Heróis divididos em conflito marcante." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme17.jpg",  "titulo" => "DIA DE MUERTOS", "desc" => "Uma celebração cultural cheia de vida." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme4.webp",  "titulo" => "ARRANHA-CÉU", "desc" => "Ação intensa em um arranha-céu em chamas." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme12.jpg",  "titulo" => "CÓDIGO ALARUM", "desc" => "Suspense e tecnologia eletrizante." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme1.webp",  "titulo" => "DEXTER", "desc" => "Um serial killer que caça criminosos em Miami." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme3.png",   "titulo" => "CORINGA", "desc" => "A origem do maior vilão de Gotham City." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme5.jpg",   "titulo" => "AVENGERS", "desc" => "Heróis se unem para salvar o mundo." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme9.jpg",   "titulo" => "VELOZES E FURIOSOS 10", "desc" => "Alta velocidade e família em primeiro lugar." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme10.jpg",  "titulo" => "GUERRA INFINITA", "desc" => "Thanos ameaça todo o universo." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme19.jpeg", "titulo" => "THE WORLD OF IT", "desc" => "O terror do universo de Stephen King." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme6.webp",  "titulo" => "HOMEM ARANHA LONGE DE CASA", "desc" => "Peter enfrenta novos desafios na Europa." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme13.jpg",  "titulo" => "SNEAKS", "desc" => "Comédia e aventura única." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme2.jpg",   "titulo" => "CARROS", "desc" => "Relâmpago McQueen em uma jornada." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme7.jpeg",  "titulo" => "SEM VOLTA PARA CASA", "desc" => "Peter enfrenta vilões do multiverso." ],
  [ "img" => "/projetotadscinetime/public/assets/images/filme11.jpg",  "titulo" => "STRANGER THINGS", "desc" => "Aventura sobrenatural em Hawkins." ],

];
?>
